Update build_if.yml

diff --git a/.github/workflows/build_if.yml b/.github/workflows/build_if.yml
--- a/.github/workflows/build_if.yml
+++ b/.github/workflows/build_if.yml
@@ -29,9 +29,16 @@ jobs:
 
       - name: Install cosign
         if: github.event_name != 'pull_request'
-        uses: sigstore/cosign-installer@7e0881f8fe90b25e305bbf0309761e9314607e25
-        with:
-          cosign-release: 'v1.9.0'
+        run: |
+          mkdir -p $HOME/.cosign
+          curl -sL https://storage.googleapis.com/cosign-releases/v1.9.0/cosign-linux-amd64 -o $HOME/.cosign/cosign
+          chmod +x $HOME/.cosign/cosign
+          echo "Expected checksum: 47e2596a38e619b72e736fd171eeeaadaf6bd22d6e87a767b339168a87b62761"
+          echo "Actual checksum: $(sha256sum $HOME/.cosign/cosign | cut -d' ' -f1)"
+          if [[ "$(sha256sum $HOME/.cosign/cosign | cut -d' ' -f1)" != "47e2596a38e619b72e736fd171eeeaadaf6bd22d6e87a767b339168a87b62761" ]]; then
+            echo "ERROR: Unable to validate cosign version: 'v1.9.0'"
+            exit 1
+          fi
 
       - name: Setup Docker buildx
         uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf
